#!/usr/bin/env bash
# Regenerates the launcher icon layers and the Play Store icon from bruce-logo.svg.
# Requires ImageMagick 7 built with librsvg (`magick -list format | grep RSVG`).
set -euo pipefail

cd "$(dirname "$0")/../.."
MASTER=docs/branding/bruce-logo.svg
RES=app/src/main/res
# The launcher icon has no background of its own; the Play icon must be an opaque square.
LAUNCHER_BACKGROUND="#00000000"
PLAY_BACKGROUND="#FFF3E6"
WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT

# High-resolution render trimmed to the drawn content.
magick -background none -density 600 "$MASTER" -trim +repage "$WORK/content.png"

# Themed-icon layer: the coat stays opaque; the white blaze and near-black eyes, nose
# and mouth become transparent, so the features survive single-colour tinting.
magick "$WORK/content.png" -background black -alpha remove -colorspace Gray \
  -fx "u>0.88 || u<0.22 ? 0 : 1" "$WORK/feature-mask.png"
magick "$WORK/content.png" -alpha extract "$WORK/shape-mask.png"
magick "$WORK/feature-mask.png" "$WORK/shape-mask.png" -compose Multiply -composite "$WORK/mono-mask.png"
magick "$WORK/mono-mask.png" -fill white -colorize 100 "$WORK/mono-mask.png" \
  -alpha off -compose CopyOpacity -composite "$WORK/monochrome.png"

# Adaptive icon layers are 108dp square; keep the head inside the central 66dp.
for density in mdpi:1 hdpi:1.5 xhdpi:2 xxhdpi:3 xxxhdpi:4; do
  name=${density%%:*}
  scale=${density##*:}
  size=$(awk "BEGIN { print int(108 * $scale) }")
  content=$(awk "BEGIN { print int(66 * $scale) }")
  mkdir -p "$RES/mipmap-$name"
  for layer in content:ic_launcher_foreground monochrome:ic_launcher_monochrome; do
    magick "$WORK/${layer%%:*}.png" -resize "${content}x${content}" -background none \
      -gravity center -extent "${size}x${size}" -strip "PNG32:$RES/mipmap-$name/${layer##*:}.png"
  done
done

# Play Store icon: 512 x 512, full-bleed background; Play applies its own corner mask.
mkdir -p docs/store
magick "$WORK/content.png" -resize 410x410 -background "$PLAY_BACKGROUND" -gravity center \
  -extent 512x512 -alpha off -strip "PNG24:docs/store/play-icon-512.png"

cat > "$RES/values/ic_launcher_background.xml" <<XML
<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by docs/branding/export-icons.sh; edit LAUNCHER_BACKGROUND there. -->
<resources>
    <color name="ic_launcher_background">$LAUNCHER_BACKGROUND</color>
</resources>
XML

echo "Icons written: launcher background $LAUNCHER_BACKGROUND, Play background $PLAY_BACKGROUND"
